-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE Category(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    category_name VARCHAR(30) NOT NULL,
);

-- Need to validate price is a number
CREATE TABLE Product(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL(15,2) NOT NULL,
    stock INT NOT NULL DEFAULT (10),
    category_id INT,
    FOREIGN KEY(category_id) REFERENCES Category(id)
        ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Tag(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tag_name VARCHAR(30)
)

CREATE TABLE ProductTag(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_id INT,
    FOREIGN KEY (product_id) REFERENCES Product(id)
    ON DELETE CASCADE ON UPDATE CASCADE
    tag_id INT,
    FOREIGN KEY(tag_id) REFERENCES Tag(tag_id)
    ON DELETE CASCADE ON UPDATE CASCADE
)
